#!/usr/bin/env sh

set -e

[ -z "${PUPPET_VERSION}" ] && script/bootstrap

bundle exec rspec

bundle exec puppet-lint --with-filename --fail-on-warnings --no-autoloader_layout-check manifests
#bundle exec puppet-lint --with-filename --fail-on-warnings --no-autoloader_layout-check modules
